### ISSUE TITLE
New logo for OdangoBot

### ISSUE THREAD

**Issue by reallinfo** [hufan-akari/OdangoBot#1]
Hello! I designed a logo for odangobot. I emphasized that letter in design. I chose the same color as the color of the telegram.  If you like one of these, I will send you a pr. If you have any other idea, I want to hear it.

![1](https://user-images.githubusercontent.com/36298335/39474187-5edadfae-4d5b-11e8-83fe-51a803e69f29.jpg)

**Comment by magic-akari** [comment]
This telegram bot is for my personal use. And it already got its avatar image.
I'm sorry to close this issue.
